### ISSUE TITLE
Arduino Pin Selection

### ISSUE THREAD

**Issue by momehussain** [NewhavenDisplay/NHD-0420CW-Slim-OLED#1]
Hi,
I was wondering why you chose pins 9 and 12 for your code.  

#define SCL 12 // Serial Clock
#define SDI 11 // Serial Data IN
#define CS9 // Chip Select

According to the Arduino Uno pinout SCL is pin 13, CS is pin 10.  Aren't pins 10 to 13 dedicated to SPI communication?

**Comment by ZPal-NHD** [comment]
Hi Momehussain,

It is not required to use pin 13 and pin 10 because the code is writing the command/data clock cycle itself.

**Comment by momehussain** [comment]
Right....I see that in the code.  Thanks!
